version: '3.1'

services:
  package-base:
    environment:
      POLARIS_TEST_DB_URL: postgres://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db

  package:
    environment:
      POLARIS_TEST_DB_URL: postgres://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db

  loader:
      image: ${PACKAGE_BASE_IMAGE}
      volumes:
        - .:/project

      entrypoint:
        - python
        - -m
        - polaris.analytics.cli.main

      environment:
        POLARIS_DB_URL: ${POLARIS_DEV_DB_URL}
        PYTHONPATH: ${PYTHONPATH}
        PYTHONDONTWRITEBYTECODE: 1

  charts:
    image: ${PACKAGE_BASE_IMAGE}
    volumes:
      - .:/project

    entrypoint:
      - python
      - -m
      - polaris.analytics.cli.charts

    environment:
      POLARIS_DB_URL: ${POLARIS_DEV_DB_URL}
      PYTHONPATH: ${PYTHONPATH}
      PYTHONDONTWRITEBYTECODE: 1



  polaris-analytics-service-dev:
    image: ${PACKAGE_BASE_IMAGE}
    command:
      - flask
      - run
      - --host
      - "0.0.0.0"
      - --port
      - "8200"
    ports:
      - "8200:8200"
    volumes:
      - .:/project
    environment:
      ENVIRONMENT: development
      FLASK_APP: polaris.analytics.service.endpoint:app
      FLASK_DEBUG: 1
      POLARIS_DB_URL: postgres://polaris:polaris@polaris-db
      AUTH_SERVICE_URL: http://polaris-services.exathink.localdev:8000
      PYTHONPATH: ${PYTHONPATH}

  polaris-db:
    image: ${POLARIS_DB_IMAGE}
    environment:
      POSTGRES_USER: polaris
      POSTGRES_PASSWORD: polaris
      POSTGRES_DB: polaris
    ports:
      - "5432"


