#!/usr/bin/env bash

#!/usr/bin/env bash

function up {
    package up polaris-db
    sleep 15
    echo "Initializing db data.."
    package run pg_restore -f /project/polaris-install/polaris/data/polaris-db.sql &>/dev/null
    echo "Starting services.."
    package polaris-admin-service compose up -d  --no-deps polaris-admin-service-dev
    package up polaris-analytics-service-dev
    echo "Services ready..."
}

function staging-debug {
    package up auth-service-staging-debug
    package up admin-service-staging-debug
    package up analytics-service-staging-debug
}

function deps {
    package up polaris-db
    sleep 15
    echo "Initializing db data.."
    package run pg_restore -f /project/polaris-install/polaris/data/polaris-db.sql &>/dev/null
    package compose up --no-deps -d auth-service
}



function down {
    echo "Stopping services.."
    package polaris-admin-service compose rm -s -f polaris-admin-service-dev
    package down
    echo "Services stopped."
}


if [[ $# -ge 1 ]]
then
    ACTION=$1
    case ${ACTION} in
        up)
            up
            ;;
        down)
            down
            ;;
        staging-debug)
            staging-debug
            ;;
        deps)
            deps
            ;;
        *)
            echo "Invalid action, must be 'up' or 'down'"
    esac
else
    echo "Usage: subsystem <up | down>"
fi
