"""add_col_changelog_to_work_items

Revision ID: 0ad7ba8a77e1
Revises: 1c38706b87b4
Create Date: 2023-11-16 15:53:04.819480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ad7ba8a77e1'
down_revision = '1c38706b87b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('changelog', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'changelog', schema='analytics')
    # ### end Alembic commands ###
