"""index_work_items_state_transitions_by_work_item_id

Revision ID: 18346d3a7dee
Revises: 32818e4e9156
Create Date: 2023-11-06 16:08:00.454502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18346d3a7dee'
down_revision = '32818e4e9156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_work_item_state_transitions_work_item_id'), 'work_item_state_transitions', ['work_item_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_work_item_state_transitions_work_item_id'), table_name='work_item_state_transitions', schema='analytics')
    # ### end Alembic commands ###
