"""add_work_items_impediment_history_table

Revision ID: 1c38706b87b4
Revises: ed9de0a41500
Create Date: 2023-10-29 22:12:08.360528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c38706b87b4'
down_revision = 'ed9de0a41500'
branch_labels = None
depends_on = None


def upgrade():

    op.create_table('work_items_impediment_history',
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('impediment_type', sa.String(), nullable=False),
    sa.Column('seq_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('cleared', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_item_id'], ['analytics.work_items.id'], ),
    sa.PrimaryKeyConstraint('work_item_id', 'impediment_type', 'seq_no'),
    schema='analytics'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_items_impediment_history', schema='analytics')
    # ### end Alembic commands ###
