"""Added organization_key to commits, renamed source_id to source_commit_id

Revision ID: 1fa2ed1eebde
Revises: b7fe3bcfccb0
Create Date: 2018-12-13 15:26:42.225837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fa2ed1eebde'
down_revision = 'b7fe3bcfccb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('organization_key', postgresql.UUID(as_uuid=True), nullable=False), schema='analytics')
    op.add_column('commits', sa.Column('source_commit_id', sa.String(), nullable=False), schema='analytics')
    op.create_index(op.f('ix_analytics_commits_organization_key'), 'commits', ['organization_key'], unique=True, schema='analytics')
    op.drop_constraint('commits_repository_key_source_id_key', 'commits', schema='analytics', type_='unique')
    op.create_unique_constraint(None, 'commits', ['repository_key', 'source_commit_id'], schema='analytics')
    op.drop_column('commits', 'source_id', schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False), schema='analytics')
    op.drop_constraint(None, 'commits', schema='analytics', type_='unique')
    op.create_unique_constraint('commits_repository_key_source_id_key', 'commits', ['repository_key', 'source_id'], schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_organization_key'), table_name='commits', schema='analytics')
    op.drop_column('commits', 'source_commit_id', schema='analytics')
    op.drop_column('commits', 'organization_key', schema='analytics')
    # ### end Alembic commands ###
