"""initial schema with commits and contributors

Revision ID: 21b99b55c132
Revises: 
Create Date: 2018-12-30 22:34:49.118612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21b99b55c132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('contributor_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_alias', sa.String(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['analytics.contributors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_contributor_aliases_contributor_id'), 'contributor_aliases', ['contributor_id'], unique=False, schema='analytics')
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_commit_id', sa.String(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('committer_contributor_name', sa.String(), nullable=True),
    sa.Column('committer_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('commit_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('committer_contributor_alias_id', sa.Integer(), nullable=False),
    sa.Column('author_contributor_name', sa.String(), nullable=True),
    sa.Column('author_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('author_date', sa.DateTime(), nullable=True),
    sa.Column('author_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('author_contributor_alias_id', sa.Integer(), nullable=False),
    sa.Column('is_orphan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_on_branch', sa.String(), nullable=True),
    sa.Column('num_parents', sa.Integer(), nullable=True),
    sa.Column('parents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['author_contributor_alias_id'], ['analytics.contributor_aliases.id'], ),
    sa.ForeignKeyConstraint(['committer_contributor_alias_id'], ['analytics.contributor_aliases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_key', 'source_commit_id'),
    schema='analytics'
    )
    op.create_index('ix_analytics_commits_author_committer_contributor_key', 'commits', ['author_contributor_key', 'committer_contributor_key'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_author_contributor_alias_id'), 'commits', ['author_contributor_alias_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_commit_date'), 'commits', ['commit_date'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_committer_contributor_alias_id'), 'commits', ['committer_contributor_alias_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_key'), 'commits', ['key'], unique=True, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_organization_key'), 'commits', ['organization_key'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_repository_key'), 'commits', ['repository_key'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_commits_repository_key'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_organization_key'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_key'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_committer_contributor_alias_id'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_commit_date'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_author_contributor_alias_id'), table_name='commits', schema='analytics')
    op.drop_index('ix_analytics_commits_author_committer_contributor_key', table_name='commits', schema='analytics')
    op.drop_table('commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_contributor_aliases_contributor_id'), table_name='contributor_aliases', schema='analytics')
    op.drop_table('contributor_aliases', schema='analytics')
    op.drop_table('contributors', schema='analytics')
    # ### end Alembic commands ###
