"""add_sprints_column_to_work_items

Revision ID: 24834954e40c
Revises: 8a74ac90c2ca
Create Date: 2023-08-09 02:10:11.203125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24834954e40c'
down_revision = '8a74ac90c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('sprints', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True), schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'sprints', schema='analytics')
    # ### end Alembic commands ###
