"""remove unique constraint from organization_key on commit

Revision ID: 24d991d217a6
Revises: 1fa2ed1eebde
Create Date: 2018-12-13 15:34:26.069818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d991d217a6'
down_revision = '1fa2ed1eebde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_commits_organization_key', table_name='commits', schema='analytics')
    op.create_index(op.f('ix_analytics_commits_organization_key'), 'commits', ['organization_key'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_commits_organization_key'), table_name='commits', schema='analytics')
    op.create_index('ix_analytics_commits_organization_key', 'commits', ['organization_key'], unique=True, schema='analytics')
    # ### end Alembic commands ###
