"""index_work_item_state_transitions_by_created_at

Revision ID: 2becdc093e7d
Revises: 18346d3a7dee
Create Date: 2023-11-06 17:58:01.918029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2becdc093e7d'
down_revision = '18346d3a7dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_work_item_state_transitions_created_at'), 'work_item_state_transitions', ['created_at'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_work_item_state_transitions_created_at'), table_name='work_item_state_transitions', schema='analytics')
    # ### end Alembic commands ###
