"""Added source_alias column to contributors

Revision ID: 35dbc6b2766f
Revises: ac8a6c099a02
Create Date: 2018-12-12 21:21:12.223048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dbc6b2766f'
down_revision = 'ac8a6c099a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('source_alias', sa.String(), nullable=False), schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'source_alias', schema='analytics')
    # ### end Alembic commands ###
