"""work_items_commits analytics schema

Revision ID: 730e9e6a5c39
Revises: 
Create Date: 2018-12-11 23:29:58.120317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730e9e6a5c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('committer_contributor_name', sa.String(), nullable=True),
    sa.Column('committer_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('commit_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('author_contributor_name', sa.String(), nullable=True),
    sa.Column('author_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('author_date', sa.DateTime(), nullable=True),
    sa.Column('author_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('parents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_orphan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_on_branch', sa.String(), nullable=True),
    sa.Column('num_parents', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('repository_key', 'source_id'),
    schema='analytics'
    )
    op.create_index('ix_analytics_commits_author_contributor_key', 'commits', ['author_contributor_key', 'committer_contributor_key'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_commit_date'), 'commits', ['commit_date'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_repository_key'), 'commits', ['repository_key'], unique=False, schema='analytics')
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('alias_for', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['alias_for'], ['analytics.contributors.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('source', 'key'),
    schema='analytics'
    )
    op.create_index('ix_contributors_key_alias_for', 'contributors', ['key', 'alias_for'], unique=False, schema='analytics')
    op.create_table('work_items_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('account_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('commit_mapping_scope', sa.String(), server_default='organization', nullable=False),
    sa.Column('commit_mapping_scope_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('work_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_bug', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('work_items_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_items_source_id'], ['analytics.work_items_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('commits_work_items',
    sa.Column('commit_id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['analytics.commits.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['analytics.work_items.id'], ),
    sa.UniqueConstraint('commit_id', 'work_item_id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_commits_work_items_commit_id'), 'commits_work_items', ['commit_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_work_items_work_item_id'), 'commits_work_items', ['work_item_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_commits_work_items_work_item_id'), table_name='commits_work_items', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_work_items_commit_id'), table_name='commits_work_items', schema='analytics')
    op.drop_table('commits_work_items', schema='analytics')
    op.drop_table('work_items', schema='analytics')
    op.drop_table('work_items_sources', schema='analytics')
    op.drop_index('ix_contributors_key_alias_for', table_name='contributors', schema='analytics')
    op.drop_table('contributors', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_repository_key'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_commit_date'), table_name='commits', schema='analytics')
    op.drop_index('ix_analytics_commits_author_contributor_key', table_name='commits', schema='analytics')
    op.drop_table('commits', schema='analytics')
    # ### end Alembic commands ###
