"""update_work_items_state_source_map

Revision ID: 7ce203a7f85b
Revises: 209f6fa05216
Create Date: 2020-03-09 12:35:14.862999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce203a7f85b'
down_revision = '209f6fa05216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
