"""Initial schema migrating key entities from repos

Revision ID: 9bb06cf6c08e
Revises: 
Create Date: 2019-01-03 14:11:23.008306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bb06cf6c08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('accounts_organizations',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['analytics.accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['analytics.organizations.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'organization_id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_accounts_organizations_account_id'), 'accounts_organizations', ['account_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_accounts_organizations_organization_id'), 'accounts_organizations', ['organization_id'], unique=False, schema='analytics')
    op.create_table('contributor_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_alias', sa.String(), nullable=False),
    sa.Column('robot', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['analytics.contributors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_contributor_aliases_contributor_id'), 'contributor_aliases', ['contributor_id'], unique=False, schema='analytics')
    op.create_table('organizations_contributors',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['analytics.contributors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['analytics.organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'contributor_id'),
    schema='analytics'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['analytics.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('vendor', sa.String(length=5), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('earliest_commit', sa.DateTime(), nullable=True),
    sa.Column('latest_commit', sa.DateTime(), nullable=True),
    sa.Column('commit_count', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['analytics.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('organization_id', 'name'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_repositories_organization_id'), 'repositories', ['organization_id'], unique=False, schema='analytics')
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('source_commit_id', sa.String(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('committer_contributor_name', sa.String(), nullable=True),
    sa.Column('committer_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('commit_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('committer_contributor_alias_id', sa.Integer(), nullable=False),
    sa.Column('author_contributor_name', sa.String(), nullable=True),
    sa.Column('author_contributor_key', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('author_date', sa.DateTime(), nullable=True),
    sa.Column('author_date_tz_offset', sa.Integer(), nullable=True),
    sa.Column('author_contributor_alias_id', sa.Integer(), nullable=False),
    sa.Column('is_orphan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_on_branch', sa.String(), nullable=True),
    sa.Column('num_parents', sa.Integer(), nullable=True),
    sa.Column('parents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['author_contributor_alias_id'], ['analytics.contributor_aliases.id'], ),
    sa.ForeignKeyConstraint(['committer_contributor_alias_id'], ['analytics.contributor_aliases.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['analytics.repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('repository_id', 'source_commit_id'),
    schema='analytics'
    )
    op.create_index('ix_analytics_commits_author_committer_contributor_key', 'commits', ['author_contributor_key', 'committer_contributor_key'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_author_contributor_alias_id'), 'commits', ['author_contributor_alias_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_commit_date'), 'commits', ['commit_date'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_committer_contributor_alias_id'), 'commits', ['committer_contributor_alias_id'], unique=False, schema='analytics')
    op.create_table('projects_repositories',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['analytics.projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['analytics.repositories.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'repository_id'),
    schema='analytics'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_repositories', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_committer_contributor_alias_id'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_commit_date'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_author_contributor_alias_id'), table_name='commits', schema='analytics')
    op.drop_index('ix_analytics_commits_author_committer_contributor_key', table_name='commits', schema='analytics')
    op.drop_table('commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_repositories_organization_id'), table_name='repositories', schema='analytics')
    op.drop_table('repositories', schema='analytics')
    op.drop_table('projects', schema='analytics')
    op.drop_table('organizations_contributors', schema='analytics')
    op.drop_index(op.f('ix_analytics_contributor_aliases_contributor_id'), table_name='contributor_aliases', schema='analytics')
    op.drop_table('contributor_aliases', schema='analytics')
    op.drop_index(op.f('ix_analytics_accounts_organizations_organization_id'), table_name='accounts_organizations', schema='analytics')
    op.drop_index(op.f('ix_analytics_accounts_organizations_account_id'), table_name='accounts_organizations', schema='analytics')
    op.drop_table('accounts_organizations', schema='analytics')
    op.drop_table('organizations', schema='analytics')
    op.drop_table('contributors', schema='analytics')
    op.drop_table('accounts', schema='analytics')
    # ### end Alembic commands ###
