"""Added committer_contributor_id and author_contributor_id to commits

Revision ID: b7fe3bcfccb0
Revises: 35dbc6b2766f
Create Date: 2018-12-12 21:42:32.625670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fe3bcfccb0'
down_revision = '35dbc6b2766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('author_contributor_id', sa.Integer(), nullable=False), schema='analytics')
    op.add_column('commits', sa.Column('committer_contributor_id', sa.Integer(), nullable=False), schema='analytics')
    op.create_index(op.f('ix_analytics_commits_author_contributor_id'), 'commits', ['author_contributor_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_commits_committer_contributor_id'), 'commits', ['committer_contributor_id'], unique=False, schema='analytics')
    op.create_foreign_key(None, 'commits', 'contributors', ['author_contributor_id'], ['id'], source_schema='analytics', referent_schema='analytics')
    op.create_foreign_key(None, 'commits', 'contributors', ['committer_contributor_id'], ['id'], source_schema='analytics', referent_schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', schema='analytics', type_='foreignkey')
    op.drop_constraint(None, 'commits', schema='analytics', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_commits_committer_contributor_id'), table_name='commits', schema='analytics')
    op.drop_index(op.f('ix_analytics_commits_author_contributor_id'), table_name='commits', schema='analytics')
    op.drop_column('commits', 'committer_contributor_id', schema='analytics')
    op.drop_column('commits', 'author_contributor_id', schema='analytics')
    # ### end Alembic commands ###
