"""add_source_priority_to_work_items

Revision ID: bdbe8ddade02
Revises: 9b99d5370dc1
Create Date: 2023-01-11 15:29:44.417417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbe8ddade02'
down_revision = '9b99d5370dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('source_priority', sa.String(), nullable=True), schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'source_priority', schema='analytics')
    # ### end Alembic commands ###
