"""Made stats and parents nullable

Revision ID: be1267b09623
Revises: 24d991d217a6
Create Date: 2018-12-14 02:45:20.447455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1267b09623'
down_revision = '24d991d217a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='analytics')
    # ### end Alembic commands ###
