"""add source_files columns to commit

Revision ID: d2b0e600f1f9
Revises: a54eb19e2ea4
Create Date: 2019-01-11 15:11:30.733814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2b0e600f1f9'
down_revision = 'a54eb19e2ea4'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('source_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['analytics.repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='analytics'
    )

    op.add_column('commits', sa.Column('source_file_actions_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='analytics')
    op.add_column('commits', sa.Column('source_file_types_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='analytics')
    op.add_column('commits', sa.Column('source_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='analytics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'source_files', schema='analytics')
    op.drop_column('commits', 'source_file_types_summary', schema='analytics')
    op.drop_column('commits', 'source_file_actions_summary', schema='analytics')
    op.drop_table('source_files', schema='analytics')
    # ### end Alembic commands ###
