"""add_indexes_for_cascades

Revision ID: f34d4cdc8f90
Revises: c3c33e6fa9ce
Create Date: 2021-12-17 16:55:42.970041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34d4cdc8f90'
down_revision = 'c3c33e6fa9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_source_files_repository_id'), 'source_files', ['repository_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_source_files_repository_id'), table_name='source_files', schema='analytics')
    # ### end Alembic commands ###
