"""add_work_item_selectors_to_teams

Revision ID: f835ec1a7a52
Revises: 8a74ac90c2ca
Create Date: 2023-08-14 17:01:30.330017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f835ec1a7a52'
down_revision = '8a74ac90c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('work_item_selectors', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True), schema='analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'work_item_selectors', schema='analytics')
    # ### end Alembic commands ###
