version: '3.1'

services:

  # Service name must be the same as docker subdirectory the Dockerfile is stored in.
  # This allows build process to figure out which services to rebuild after a commit.
  polaris-python-build-base:
    image: polaris-python-build-base
    build: ./docker/polaris-python-build-base

  # Service name must be the same as docker subdirectory the Dockerfile is stored in.
  # This allows build process to figure out which services to rebuild after a commit.
  polaris-gitlab-ci:
    image: polaris-gitlab-ci
    build: ./docker/polaris-gitlab-ci

# Service name must be the same as docker subdirectory the Dockerfile is stored in.
  # This allows build process to figure out which services to rebuild after a commit.
  polaris-python-builder-db:
    image: polaris-python-builder-db
    build: ./docker/polaris-python-builder-db

# Service name must be the same as docker subdirectory the Dockerfile is stored in.
  # This allows build process to figure out which services to rebuild after a commit.
  polaris-python-release-db:
    image: polaris-python-release-db
    build: ./docker/polaris-python-release-db


# Service name must be the same as docker subdirectory the Dockerfile is stored in.
  # This allows build process to figure out which services to rebuild after a commit.
  polaris-postgres:
    image: polaris-postgres
    build: ./docker/polaris-postgres